name: .NET CI

on:
  push:
    branches: [ master, main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore **/*.csproj
    - name: Build
      run: dotnet build src/*.csproj -c Release --no-restore
    - name: Test
      run: dotnet test tests/Unit/Unit.csproj -c Release --no-build
